language: go
services: docker
before_install:
        - gem install capistrano
before_script:
        - env | sort
        - wget --user="$BITBUCKET_EMAIL" --password="$BITBUCKET_PASS" https://bitbucket.org/arpitjindal97/secrets/raw/master/aws-doorlock-ssh.key
        - wget --user="$BITBUCKET_EMAIL" --password="$BITBUCKET_PASS" https://bitbucket.org/arpitjindal97/secrets/raw/master/docker.sh 
        - wget --user="$BITBUCKET_EMAIL" --password="$BITBUCKET_PASS" https://bitbucket.org/arpitjindal97/secrets/raw/master/msmartpay.sh
        - wget --user="$BITBUCKET_EMAIL" --password="$BITBUCKET_PASS" https://bitbucket.org/arpitjindal97/secrets/raw/master/server-1.sh
        - ls -alh && eval $(cat docker.sh) && eval $(msmartpay.sh) && eval $(server-1.sh)
        - image="$DOCKER_USERNAME/telegram-msmartpay:latest"
script:
        - go build -ldflags "-X main.msmartpay_password=$msmartpay_password -X main.msmartpay_email=$msmartpay_email" *.go
        - rm *.go
        - ls -alh
        - docker build -t $image .
after_script:
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push $image
        - cap production deploy
