language: go
services: docker
before_install:
        - gem install capistrano
before_script:
        - env | sort
        - image="arpitjindal1997/telegram-msmartpay:latest"
script:
        - go build -ldflags "-X main.msmartpay_password=$msmartpay_password -X main.msmartpay_email=$msmartpay_email" *.go
        - rm *.go
        - ls -alh
        - docker build -t $image .
after_script:
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push $image
        - cap production deploy
