language: go
services: docker
before_install:
        - gem install capistrano
before_script:
        - env | sort
        - mkdir secrets && cd secrets
        - wget --user="$BITBUCKET_EMAIL" --password="$BITBUCKET_PASS" -i ../urls.txt
        - ls -alh && eval "$(cat *.sh)" && cd ..
        - image="$DOCKER_IMG"
script:
        - go build -ldflags "-X main.msmartpay_password=$msmartpay_password -X main.msmartpay_email=$msmartpay_email -X main.telegram_bot_api=$telegram_bot_api" *.go
        - rm *.go
        - ls -alh
        - docker build -t $image .
after_script:
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push $image
        - cap production deploy
